### ISSUE TITLE
[Bug] Error Code 3: API Usage Error in `addAttention` (mScopedOps check failed) during full model compilation

### ISSUE THREAD

**Issue by MosRat** [NVIDIA/TensorRT-RTX#26]
**Describe the bug**

I am encountering a TensorRT internal error when compiling an ONNX model using `NvTensorRTRTXExecutionProvider`.
The error occurs specifically at an `Attention` node. The log indicates an API Usage Error: `condition: mScopedOps.size() == mGraph.scopedOps.size()` inside `nvinfer1::Network::addAttention`.
**Steps to reproduce**
1. Load the attached full model `encoder_fp16.onnx`.
2. Configure `ort.SessionOptions` with `NvTensorRTRTXExecutionProvider`.
3. Use `ort.ModelCompiler` to compile the model.
4. Observe the crash/error log.
5. (Contrast) Load the attached `attention_opset23.onnx` (subgraph) and repeat the steps -> It succeeds.

**Code sample**
1. python
```python
import onnxruntime as ort

# Failure case
input_path = r"path\to\encoder_fp16.onnx"
output_path = r"path\to\encoder_rtx.onnx"

session_options = ort.SessionOptions()
session_options.add_provider(
    "NvTensorRTRTXExecutionProvider",
    { },
)

model_compiler = ort.ModelCompiler(
    session_options, input_path, embed_compiled_data_into_model=True
)
model_compiler.compile_to_file(output_path)
```

**Error messages**
```text
2025-11-26 21:07:50.9396782 [E:onnxruntime:Default, nv_execution_provider.h:47 onnxruntime::TensorrtLogger::log] [2025-11-26 13:07:50   ERROR] INetworkDefinition::addAttention: Error Code 3: API Usage Error (Parameter check failed, condition: mScopedOps.size() == mGraph.scopedOps.size().  In nvinfer1::Network::addAttention at C:\_src\optimizer\api\network.cpp:2125)
2025-11-26 21:07:50.9444381 [E:onnxruntime:Default, nv_execution_provider.h:47 onnxruntime::TensorrtLogger::log] [2025-11-26 13:07:50   ERROR] ModelImporter.cpp:137: While parsing node number 53 [Attention -> "/encoder/layers.0/blocks.1/attention/self/Attention_output_4d_cnt1"]:
...
op_type: "Attention"
attribute {
  name: "softcap"
  f: 0
  type: FLOAT
}
attribute {
  name: "kv_num_heads"
  i: 3
  type: INT
}
```
[attention_opset23.onnx](https://huggingface.co/MosRat/mixtex_onnx/blob/main/attention_opset23.onnx)
[encoder_fp16.onnx](https://huggingface.co/MosRat/mixtex_onnx/blob/main/encoder_fp16.onnx)

2. cli
```text
&&&& RUNNING TensorRT-RTX.tensorrt_rtx [TensorRT v10200] [b54] # C:\Program Files\NVIDIA Corporation\TensorRT-RTX-1.2.0.54\bin\tensorrt_rtx.exe --onnx=C:\Users\taizun\Desktop\encoder_fp16.onnx --shapes=data:1x3x448x448 --noDataTransfers --rtxCudaGraphStrategy=wholeGraph --useSpinWait
[11/26/2025-21:58:14] [I] === Model Options ===
[11/26/2025-21:58:14] [I] Format: ONNX
[11/26/2025-21:58:14] [I] Model: C:\Users\taizun\Desktop\encoder_fp16.onnx
[11/26/2025-21:58:14] [I] Output:
[11/26/2025-21:58:14] [I] === Build Options ===
[11/26/2025-21:58:14] [I] Memory Pools: workspace: default, dlaSRAM: default, dlaLocalDRAM: default, dlaGlobalDRAM: default, tacticSharedMem: default
[11/26/2025-21:58:14] [I] avgTiming: 8
[11/26/2025-21:58:14] [I] Refit: Disabled
[11/26/2025-21:58:14] [I] Strip weights: Disabled
[11/26/2025-21:58:14] [I] Version Compatible: Disabled
[11/26/2025-21:58:14] [I] Sparsity: Disabled
[11/26/2025-21:58:14] [I] Skip inference: Disabled
[11/26/2025-21:58:14] [I] Save engine:
[11/26/2025-21:58:14] [I] Load engine:
[11/26/2025-21:58:14] [I] Profiling verbosity: 0
[11/26/2025-21:58:14] [I] Tactic sources: Using default tactic sources
[11/26/2025-21:58:14] [I] timingCacheMode: local
[11/26/2025-21:58:14] [I] timingCacheFile:
[11/26/2025-21:58:14] [I] Enable Compilation Cache: Enabled
[11/26/2025-21:58:14] [I] Enable Monitor Memory: Disabled
[11/26/2025-21:58:14] [I] errorOnTimingCacheMiss: Disabled
[11/26/2025-21:58:14] [I] Preview Features: Use default preview flags.
[11/26/2025-21:58:14] [I] MaxAuxStreams: -1
[11/26/2025-21:58:14] [I] BuilderOptimizationLevel: -1
[11/26/2025-21:58:14] [I] MaxTactics: -1
[11/26/2025-21:58:14] [I] Calibration Profile Index: 0
[11/26/2025-21:58:14] [I] Weight Streaming: Disabled
[11/26/2025-21:58:14] [I] Runtime Platform: Same As Build
[11/26/2025-21:58:14] [I] Debug Tensors:
[11/26/2025-21:58:14] [I] Distributive Independence: Disabled
[11/26/2025-21:58:14] [I] Mark Unfused Tensors As Debug Tensors: Disabled
[11/26/2025-21:58:14] [I] Input(s)s format: fp32:CHW
[11/26/2025-21:58:14] [I] Output(s)s format: fp32:CHW
[11/26/2025-21:58:14] [I] Input build shape (profile 0): data=1x3x448x448+1x3x448x448+1x3x448x448
[11/26/2025-21:58:14] [I] Input calibration shapes: model
[11/26/2025-21:58:14] [I] === System Options ===
[11/26/2025-21:58:14] [I] Device: 0
[11/26/2025-21:58:14] [I] DLACore:
[11/26/2025-21:58:14] [I] === Inference Options ===
[11/26/2025-21:58:14] [I] Batch: Explicit
[11/26/2025-21:58:14] [I] Input inference shape : data=1x3x448x448
[11/26/2025-21:58:14] [I] Iterations: 10
[11/26/2025-21:58:14] [I] Duration: 3s (+ 200ms warm up)
[11/26/2025-21:58:14] [I] Sleep time: 0ms
[11/26/2025-21:58:14] [I] Idle time: 0ms
[11/26/2025-21:58:14] [I] Inference Streams: 1
[11/26/2025-21:58:14] [I] ExposeDMA: Disabled
[11/26/2025-21:58:14] [I] Data transfers: Disabled
[11/26/2025-21:58:14] [I] Spin-wait: Enabled
[11/26/2025-21:58:14] [I] Multithreading: Disabled
[11/26/2025-21:58:14] [I] CUDA Graph: Disabled
[11/26/2025-21:58:14] [I] Separate profiling: Disabled
[11/26/2025-21:58:14] [I] Time Deserialize: Disabled
[11/26/2025-21:58:14] [I] Time Refit: Disabled
[11/26/2025-21:58:14] [I] NVTX verbosity: 0
[11/26/2025-21:58:14] [I] Persistent Cache Ratio: 0
[11/26/2025-21:58:14] [I] Optimization Profile Index: 0
[11/26/2025-21:58:14] [I] Weight Streaming Budget: 100.000000%
[11/26/2025-21:58:14] [I] Runtime Cache File:
[11/26/2025-21:58:14] [I] Dynamic Shapes Specialization Strategy: lazy
[11/26/2025-21:58:14] [I] RTX CUDA Graph Strategy: wholeGraph
[11/26/2025-21:58:14] [I] Inputs:
[11/26/2025-21:58:14] [I] Debug Tensor Save Destinations:
[11/26/2025-21:58:14] [I] Dump All Debug Tensor in Formats:
[11/26/2025-21:58:14] [I] === Reporting Options ===
[11/26/2025-21:58:14] [I] Verbose: Disabled
[11/26/2025-21:58:14] [I] Averages: 10 inferences
[11/26/2025-21:58:14] [I] Percentiles: 90,95,99
[11/26/2025-21:58:14] [I] Dump refittable layers:Disabled
[11/26/2025-21:58:14] [I] Dump output: Disabled
[11/26/2025-21:58:14] [I] Profile: Disabled
[11/26/2025-21:58:14] [I] Export timing to JSON file:
[11/26/2025-21:58:14] [I] Export output to JSON file:
[11/26/2025-21:58:14] [I] Export profile to JSON file:
[11/26/2025-21:58:14] [I]
[11/26/2025-21:58:14] [I]
[11/26/2025-21:58:14] [I] TensorRT version: 1.2.0 RTX
[11/26/2025-21:58:14] [W] [TRT] In JIT build, strongly typed is enabled by default.
[11/26/2025-21:58:14] [I] Start parsing network model.
[11/26/2025-21:58:14] [I] [TRT] ----------------------------------------------------------------
[11/26/2025-21:58:14] [I] [TRT] Input filename:   C:\Users\taizun\Desktop\encoder_fp16.onnx
[11/26/2025-21:58:14] [I] [TRT] ONNX IR version:  0.0.10
[11/26/2025-21:58:14] [I] [TRT] Opset version:    23
[11/26/2025-21:58:14] [I] [TRT] Producer name:    pytorch
[11/26/2025-21:58:14] [I] [TRT] Producer version: 2.7.1
[11/26/2025-21:58:14] [I] [TRT] Domain:
[11/26/2025-21:58:14] [I] [TRT] Model version:    0
[11/26/2025-21:58:14] [I] [TRT] Doc string:
[11/26/2025-21:58:14] [I] [TRT] ----------------------------------------------------------------
[11/26/2025-21:58:14] [E] Error[3]: INetworkDefinition::addAttention: Error Code 3: API Usage Error (Parameter check failed, condition: mScopedOps.size() == mGraph.scopedOps.size().  In nvinfer1::Network::addAttention at C:\_src\optimizer\api\network.cpp:2125)
[11/26/2025-21:58:14] [E] [TRT] ModelImporter.cpp:137: While parsing node number 54 [Attention -> "/encoder/layers.0/blocks.1/attention/self/Attention_output_4d_cnt1"]:
[11/26/2025-21:58:14] [E] [TRT] ModelImporter.cpp:138: --- Begin node ---
input: "/encoder/layers.0/blocks.1/attention/self/Attention_Q_transpose_cnt1"
input: "/encoder/layers.0/blocks.1/attention/self/Attention_K_transpose_cnt1"
input: "/encoder/layers.0/blocks.1/attention/self/Attention_V_transpose_cnt1"
input: "com.microsoft::Attention_423"
output: "/encoder/layers.0/blocks.1/attention/self/Attention_output_4d_cnt1"
name: "/encoder/layers.0/blocks.1/attention/self/Attention"
op_type: "Attention"
attribute {
  name: "kv_num_heads"
  i: 3
  type: INT
}
attribute {
  name: "q_num_heads"
  i: 3
  type: INT
}
domain: ""

[11/26/2025-21:58:14] [E] [TRT] ModelImporter.cpp:139: --- End node ---
[11/26/2025-21:58:14] [E] [TRT] ModelImporter.cpp:142: ERROR: ModelImporter.cpp:362 In function parseNode:
[6] Invalid Node - /encoder/layers.0/blocks.1/attention/self/Attention
INetworkDefinition::addAttention: Error Code 3: API Usage Error (Parameter check failed, condition: mScopedOps.size() == mGraph.scopedOps.size().  In nvinfer1::Network::addAttention at C:\_src\optimizer\api\network.cpp:2125)
[11/26/2025-21:58:14] [E] Failed to parse onnx file
[11/26/2025-21:58:14] [I] Finished parsing network model. Parse time: 0.160789
[11/26/2025-21:58:14] [E] Parsing model failed
[11/26/2025-21:58:14] [E] Failed to create engine from model or file.
[11/26/2025-21:58:14] [E] Engine set up failed
&&&& FAILED TensorRT-RTX.tensorrt_rtx [TensorRT v10200] [b54] # C:\Program Files\NVIDIA Corporation\TensorRT-RTX-1.2.0.54\bin\tensorrt_rtx.exe --onnx=C:\Users\taizun\Desktop\encoder_fp16.onnx --shapes=data:1x3x448x448 --noDataTransfers --rtxCudaGraphStrategy=wholeGraph --useSpinWait
```

**Expected behavior**

The full model should compile successfully, engine file will be compiled into the onnx file.
**Environment**
 - **TensorRT-RTX version:** 1.2.0.54
 - **ONNX Runtime version:** 1.24.0
 - **GPU:** NVIDIA GeForce RTX 3060
 - **Operating system:** Windows 11 (25H2)
 - **CUDA version:** 12.9
 - **CPU architecture:** x86_64

**Screenshots**

**Additional context**

**Comment by MosRat** [comment]
It now works with trt-rtx v1.3.0 and onnx opset version 23 `Attention` op in fp16/bf16 precision, which can be fuse to something like `_gemm_mha_v2_xxxxx`. Just export pytorch models with `F.scaled_dot_product_attention`  and `opset_version=23` and trt will work smoothly.(I tried `opset_version=21` and it also work without fused nodes in onnx files but the same kernel `_gemm_mha_v2_xxxxx` appeared in the profile.)
